name: 'GitHub Enterprise Backup Utilities Action'
description: 'A GitHub Action to backup and restore GitHub Enterprise'
inputs:
  ghe-hostname:  # hostname of the GitHub Enterprise instance
    description: 'The hostname of the GitHub Enterprise instance'
    required: true
    default: 'github.example.com'
  verbose:  # verbose output
    description: 'Verbose output'
    required: false
    default: 'true'
  restore:  # restore from backup
    description: 'Restore from backup'
    required: false
    default: 'false'
  ssh-private-key:  # SSH private key
    description: 'SSH private key'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    # Clone the [GitHub Enterprise Backup Utilities](https://github.com/github/backup-utils) repository
    - run: git clone https://github.com/github/backup-utils.git
      shell: bash
    # Populate the `backup-utils/backup.config` file with the GitHub Enterprise hostname, and `GHE_DATA_DIR="data"`
    - run: |
        echo 'GHE_HOSTNAME="${{ inputs.ghe-hostname }}"' > backup-utils/backup.config
        echo 'GHE_DATA_DIR="${{ github.workspace }}/data"' >> backup-utils/backup.config
        # Make the data directory
        mkdir -p ${{ github.workspace }}/data
      shell: bash
    # Get SSH private key from GitHub Secrets and place in `.ssh/` directory. Base the filename on the type of key. Accepts RSA and ED25519 keys.
    - run: |
        mkdir -p ~/.ssh
        if [[ "${{ inputs.ssh-private-key }}" == *"BEGIN RSA PRIVATE KEY"* ]]; then
          echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        elif [[ "${{ inputs.ssh-private-key }}" == *"BEGIN OPENSSH PRIVATE KEY"* ]]; then
          echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        else
          echo "SSH private key is not a valid RSA or ED25519 key."
          exit 1
        fi
      shell: bash
    
    # Set SSH client options "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no"
    - run: |
        echo "Host *" > ~/.ssh/config
        echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
        echo "  StrictHostKeyChecking=no" >> ~/.ssh/config
        echo "  PasswordAuthentication=no" >> ~/.ssh/config
      shell: bash
    
    # Run `ghe-host-check` to verify the GitHub Enterprise instance is reachable
    - run: backup-utils/bin/ghe-host-check ${{ inputs.ghe-hostname }}
      shell: bash

    # If the restore input is set to true, restore from backup
    - run: |
        if [ ${{ inputs.restore }} = true ]; then
          ./backup-utils/bin/ghe-restore -v ${{ inputs.ghe-hostname }}
        fi
        exit 0
      shell: bash
    # If the restore input is not set to true, backup the GitHub Enterprise instance, setting the verbose flag if the verbose input is set to true
    - run: |
        if [ ${{ inputs.restore }} != true ]; then
          if [ ${{ inputs.verbose }} = true ]; then
            GHE_HOSTNAME=${{ inputs.ghe-hostname }} ./backup-utils/bin/ghe-backup -v
          else
            GHE_HOSTNAME=${{ inputs.ghe-hostname }} ./backup-utils/bin/ghe-backup
          fi
        fi
      shell: bash
    ## Compress the data directory into a tarball
    #- run: tar -czf data-${{ inputs.ghe-hostname }}-${{ github.run_id }}.tar.gz ${{ github.workspace }}/data
    #  shell: bash
    ## Upload the tarball as an artifact with actions/upload-artifact
    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: data-${{ inputs.ghe-hostname }}-${{ github.run_id }}.tar.gz
    #    path: data-${{ inputs.ghe-hostname }}-${{ github.run_id }}.tar.gz
    ## Upload the data directory as an artifact with actions/upload-artifact
    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: data-${{ inputs.ghe-hostname }}-${{ github.run_id }}
    #    path: data
